import { configureStore, createSlice } from "@reduxjs/toolkit";

const initialState = {
    exams: [
        { id: 1, title: "Exam 1", professor: "McCloskey, Jim", dateOpen: 1656343343694, dateClose: 1656363343694, timeLimit: 120 },
        { id: 2, title: "Exam 1", professor: "Purtee, Steven", dateOpen: 1656343343694, dateClose: 1656363343694, timeLimit: 120 },
        { id: 3, title: "Exam 2", professor: "McCloskey, Jim", dateOpen: 1656344343694, dateClose: 1656363643694, timeLimit: 120 },
        { id: 4, title: "Midterm", professor: "Dagit, Robert", dateOpen: 1656343343694, dateClose: 1656363343694, timeLimit: 120 },
    ],
    sections: [
        { "Id": 1, "Title": "Overflow", "RowCount": 2, "MaxRow": 14 },
        { "Id": 2, "Title": "Main Room", "RowCount": 9, "MaxRow": 8 },
        { "Id": 3, "Title": "OSD", "RowCount": 1, "MaxRow": 2 }
    ],
    seating:
        [
            {
                "SeatId": "J01",
                "Type": 'Computer',
                "Section": 1,
                "DefaultStatus": 4,
                "Status": 4,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "J02",
                "Type": 'Computer',
                "Section": 1,
                "DefaultStatus": 4,
                "Status": 4,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "J03",
                "Type": 'Computer',
                "Section": 1,
                "DefaultStatus": 4,
                "Status": 4,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "J04",
                "Type": 'Computer',
                "Section": 1,
                "DefaultStatus": 4,
                "Status": 4,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "J05",
                "Type": 'Computer',
                "Section": 1,
                "DefaultStatus": 4,
                "Status": 4,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "J06",
                "Type": 'Computer',
                "Section": 1,
                "DefaultStatus": 4,
                "Status": 4,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "J07",
                "Type": 'Computer',
                "Section": 1,
                "DefaultStatus": 4,
                "Status": 4,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "J08",
                "Type": 'Computer',
                "Section": 1,
                "DefaultStatus": 4,
                "Status": 4,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "J09",
                "Type": 'Computer',
                "Section": 1,
                "DefaultStatus": 4,
                "Status": 4,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "J10",
                "Type": 'Computer',
                "Section": 1,
                "DefaultStatus": 4,
                "Status": 4,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "J11",
                "Type": 'Computer',
                "Section": 1,
                "DefaultStatus": 4,
                "Status": 4,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "J12",
                "Type": 'Computer',
                "Section": 1,
                "DefaultStatus": 4,
                "Status": 4,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "J13",
                "Type": 'Computer',
                "Section": 1,
                "DefaultStatus": 4,
                "Status": 4,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "J14",
                "Type": 'Computer',
                "Section": 1,
                "DefaultStatus": 4,
                "Status": 4,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "A01",
                "Type": 'Paper',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "A02",
                "Type": 'Computer',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "A03",
                "Type": 'Paper',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "A04",
                "Type": 'Computer',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "A05",
                "Type": 'Paper',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "B06",
                "Type": 'Paper',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "B07",
                "Type": 'Computer',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "B08",
                "Type": 'Paper',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "B09",
                "Type": 'Computer',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "B10",
                "Type": 'Paper',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "B11",
                "Type": 'Computer',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "C12",
                "Type": 'Paper',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "C13",
                "Type": 'Computer',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "C14",
                "Type": 'Paper',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "C15",
                "Type": 'Computer',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "C16",
                "Type": 'Paper',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "C17",
                "Type": 'Computer',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "D18",
                "Type": 'Computer',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "D19",
                "Type": 'Paper',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "D20",
                "Type": 'Paper',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "D21",
                "Type": 'Computer',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "D22",
                "Type": 'Paper',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "D23",
                "Type": 'Computer',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "E24",
                "Type": 'Paper',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "E25",
                "Type": 'Computer',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "E26",
                "Type": 'Computer',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "E27",
                "Type": 'Paper',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "E28",
                "Type": 'Computer',
                "Section": 2,
                "DefaultStatus": 1,
                "Status": 1,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "Room A",
                "Type": 'OSD',
                "Section": 3,
                "Status": 2,
                "DefaultStatus": 2,
                "Student": null,
                "Exam": null,
            },
            {
                "SeatId": "Room B",
                "Type": 'OSD',
                "Section": 3,
                "DefaultStatus": 2,
                "Status": 2,
                "Student": null,
                "Exam": null,
            }
        ]
};

const seatingSlice = createSlice({
    name: "seating",
    initialState,
    reducers: {

    }
});

export const SeatingStore = configureStore({
    reducer: seatingSlice.reducer
});

export type RootState = ReturnType<typeof SeatingStore.getState>;
export type AppDispatcch = typeof SeatingStore.dispatch;